[workspace]
members = [
    "node",
    "pallets/template",
    "pallets/poe",
    "pallets/kitties",
    "pallets/ocw",
    "runtime",
]
exclude = [
    "erc20",
]
[profile.release]
panic = "unwind"
